---
# tasks file for mock_osi_role# mock_osi_role/tasks/main.yml

- name: Deploy OSI App
  hosts: customer-X-osi-app-server
  vars:
    # Load variables from vars/main.yml
    - "{{ lookup('vars', 'osi_app_name') }}"
    - "{{ lookup('vars', 'osi_app_version') }}"
    - "{{ lookup('vars', 'osi_app_port') }}"
    - "{{ lookup('vars', 'osi_app_env') }}"
  tasks:
    - name: Ensure OSI app is installed
      apt:
        name: "{{ osi_app_name }}"
        state: present

    - name: Start OSI app service
      service:
        name: "{{ osi_app_name }}"
        state: started
        enabled: yes

    - name: Configure OSI app
      template:
        src: osi_app_config.j2
        dest: /etc/osi-app/config.yml
      vars:
        app_port: "{{ osi_app_port }}"
        app_env: "{{ osi_app_env }}"

    - name: Ensure OSI app is running
      service:
        name: "{{ osi_app_name }}"
        state: started

    - name: Ensure OSI app is enabled
      service:
        name: "{{ osi_app_name }}"
        enabled: yes
  