---
# tasks file for mock_api_role

- name: Custom API setup
  hosts: api_servers
  vars:
    api_endpoint: 'https://api.customer.com/v1/data'
    api_token: 'token_customer_789'
  tasks:
    - name: Fetch data from customer API
      ansible.builtin.uri:
        url: "{{ api_endpoint }}"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
        return_content: yes
      register: api_response

    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: 'http://www.example.com'

    - name: Create a JIRA issue
      ansible.builtin.uri:
        url: https://your.jira.example.com/rest/api/2/issue/
        user: "{{ customer_username }}"
        password: "{{ customer_password }}"
        method: POST
        body: "{{ lookup('ansible.builtin.file','issue.json') }}"
        force_basic_auth: true
        status_code: 201
        body_format: json