---
# defaults file for mock_template_role

services:
  - name: "Service1"
    port: 8080
    enabled: true
  - name: "Service2"
    port: 9090
    enabled: false

client_id: 'customer123'
client_secret: 's3cr3t_key'