---
# tasks file for mock_db_role

- name: Create database users
  hosts: database_servers
  vars:
    db_users:
      - user: dbadmin-john-doe
        password: "{{ dbadmin_pass }}"
      - user: dbuser-alex-doe
        password: "{{ dbuser_pass }}"
  tasks:
    - name: Create database user using hashed password with all database privileges
      community.mysql.mysql_user:
        name: bob
        password: '*EE0D72C1085C46C5278932678FBE2C6A782821B4'
        encrypted: true
        priv: '*.*:ALL'
        state: present

    - name: Create database users
      community.mysql.mysql_user:
        name: "{{ item.user }}"
        password: "{{ item.password }}"
        priv: "*.*:ALL"
        state: present
      loop: "{{ db_users }}"