---
# tasks file for mock_template_role

- name: Deploy configuration template
  hosts: all
  tasks:
    - name: Deploy configuration template
      ansible.builtin.template:
        src: my_app_template.j2
        dest: /etc/my_app/config.cfg

- name: Update certs on website
  hosts: web_servers
  vars:
    domain_name: 'customer-website.com'
    ssl_cert_path: '/etc/ssl/certs/customer_cert.pem'
  tasks:
    - name: Configure web server
      ansible.builtin.template:
        src: my_app_template2.j2
        dest: "/etc/nginx/sites-available/{{ domain_name }}"
      notify: restart nginx