---
# tasks file for mock_email_role

- name: Setup Emails
  hosts: mail_servers
  vars:
    email_user: 'alert@customer.com'
    smtp_password: 'secure_password'
  tasks:
    - name: Configure SMTP settings
      ansible.builtin.copy:
        content: |
          [smtp]
          user = {{ email_user }}
          password = {{ smtp_password }}
        dest: /etc/mail/smtp.conf