---
# tasks file for mock_azure_role
- name: Fetch Credential from Azure Key Vault
  hosts: localhost
  gather_facts: false

  vars:
    ansible_python_interpreter: /home/myusername123/pyvirt/azure/bin/python
    azure_subscription_id: "12345678-1234-1234-1234-123456789abc"
    azure_client_id: "87654321-4321-4321-4321-abcdefabcdef"
    azure_client_secret: "mock_client_secret"
    azure_tenant_id: "tenant_id_example"
    key_vault_name: ansible-demo-123
    key_vault_url: https://ansible-demo-123.vault.azure.net/
    secret_name: demosecret101
    secret_dest: "/tmp/mock_secret"  # Mock path to save secret

  tasks:
    - name: Fetch Key Vault Secret
      azure.azcollection.azure_rm_keyvaultsecret:
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_client_secret }}"
        tenant: "{{ azure_tenant_id }}"
        keyvault_uri: "https://{{ key_vault_name }}.vault.azure.net/"
        secret_name: "{{ secret_name }}"
        dest: "{{ secret_dest }}"
      register: secret_result

    - name: Get latest version of specific secret
      azure.azcollection.azure_rm_keyvaultsecret_info:
        vault_uri: "https://{{ key_vault_name }}.vault.azure.net/"
        name: "{{ secret_name }}"
      register: secret_result

    - name: Create a secret
      azure.azcollection.azure_rm_keyvaultsecret:        
        secret_name: MySecret
        secret_value: "mock_secret_value"  # Mock secret value
        keyvault_uri: https://ansible-demo-123.vault.azure.net/        
        tags:
            testing: "mock_testing"
            delete: "never"

    - name: Display Secret
      ansible.builtin.debug:        
        msg: "{{ secret_result  }}"

    - name: Get secret value
      azure.azcollection.azure_rm_keyvaultsecret_info:        
        vault_uri: "{{ key_vault_url }}"
        name: "{{ secret_name }}"
      register: kvSecret
    - debug:
        msg: "{{ kvSecret }}"
    - name: set secret fact
      set_fact: secretValue="{{ kvSecret['secrets'][0]['secret'] }}"
    
    - debug:
        msg: "{{ secretValue }}"
    - name: Set key vault secret fact
      ansible.builtin.set_fact:        
        secretValue={{ lookup('azure.azcollection.azure_keyvault_secret', secret_name, vault_url=key_vault_url, client_id=azure_client_id, secret=azure_client_secret, tenant_id=azure_tenant_id) }}