---
# tasks file for mock_custom_credentials

- name: Copy deploy key
  hosts: app_servers
  vars:
    deploy_user: 'deploy_customer'
    deploy_key: '/path/to/customer/private_key'
  tasks:
    - name: Copy deploy key
      ansible.builtin.copy:
        src: "{{ deploy_key }}"
        dest: /home/{{ deploy_user }}/.ssh/id_rsa
        owner: "{{ deploy_user }}"
        mode: '0600'